export default async function StaticPage() {
  // 1. ***State***
  // 2. ***Functions***
  const response = await fetch(
    "http://localhost:3000//api/articles/articlesTab.json"
  );
  const data = await response.json();

  const stringifyData = JSON.stringify(data);

  // const renderArticles = stringifyData
  // 3. ***Functions***

  return (
    <>
      <section>
        <h1>Page generated by Server Side </h1>
      </section>
      <section>
        <ul>{stringifyData}</ul>
      </section>
    </>
  );
}
